name: "AzureCLI"
version: "1.4"
slug: azcli
description: "Run Azure CLI commands on Raspberry Pi 4 (64-bit)"
startup: services
boot: auto
init: false
ingress: false
arch:
  - aarch64
host_network: true
map:
  - config:rw
options:
  tenant_id: ""
  client_id: ""
  client_secret: ""
schema:
  tenant_id: str
  client_id: str
  client_secret: str
